keys:
  - &kruppe age1gnkarhdg8rmy07qwt74f2aqpqyrj5cd74hqr3r0tmxnhzadea5hqt3v6ew
  - &mappo age1vkyzl5e4pafvr97rfast9w7wnt4uv6hwrscl4mgnywhtsv3spgns0hwx5d
  - &baruk age19nv3em6k4g2lkp0kug8hvus2wqf2286e29h04x8qpdqm3s2g7svq9l2x0t
  - &karsa age174jkrmnauzpprvf4yz5qqmed7w64fkuf8wprnkssavt90vvpxpvs4dtmyr
  - &tehol age19whva0zqzvd9ka23clkvtjtv9csy2gu99y7w8m7crkyr46t2hdyqznr9ap
  - &samar age1ae9luv3zazx9dwp4hu9d5m4l8dxl3vkwgurhq3x80fpv6aeskscsp2249q
  - &matt age195usngw73768975fq0h6uxkj8dsn9e6a8ufkwcuj88lxa2damv6qy4ktf8
creation_rules:
  - path_regex: secrets/kruppe.yaml$
    key_groups:
      - age:
        - *kruppe
        - *mappo
        - *matt
        - *karsa
  - path_regex: secrets/baruk.yaml$
    key_groups:
      - age:
        - *baruk
        - *mappo
        - *matt
        - *karsa
  - path_regex: secrets/karsa.yaml$
    key_groups:
      - age:
        - *karsa
        - *matt
        - *mappo
  - path_regex: secrets/tailscale.yaml$
    key_groups:
      - age:
        - *baruk
        - *karsa
        - *kruppe
        - *mappo
        - *samar
        - *tehol
        - *matt
