keys:
  - &kruppe age1gnkarhdg8rmy07qwt74f2aqpqyrj5cd74hqr3r0tmxnhzadea5hqt3v6ew
  - &mappo age1vkyzl5e4pafvr97rfast9w7wnt4uv6hwrscl4mgnywhtsv3spgns0hwx5d
creation_rules:
  - path_regex: secrets/kruppe.yaml$
    key_groups:
      - age:
        - *kruppe
        - *mappo
