#############################
### ENVIRONMENT VARIABLES ###
#############################

# Noctalia lock screen uses this PAM service — must match the one with fprintAuth = true
env = NOCTALIA_PAM_SERVICE,noctalia

################
### MONITORS ###
################

$mon1=desc:Lenovo Group Limited 0x4146
$mon2=desc:AOC Q27G2G3R3B 137P6HA011487

monitor=$mon1,3840x2400@60Hz,0x0,2
monitor=$mon2,2560x1440@143.91Hz,-2560x0,1

##############################
### WINDOWS AND WORKSPACES ###
##############################

workspace=1, monitor:$mon2, default:true
workspace=2, monitor:$mon2
workspace=3, monitor:$mon2
workspace=4, monitor:$mon2
workspace=5, monitor:$mon2
workspace=6, monitor:$mon2
workspace=7, monitor:$mon2
workspace=8, monitor:$mon2
workspace=9, monitor:$mon2, on-created-empty: ghostty -e spotify_player

#############
### INPUT ###
#############

input {
  kb_layout = us
  kb_variant =
  kb_model =
  kb_options = ctrl:nocaps
  kb_rules =

  follow_mouse = 1

  sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

  touchpad {
      natural_scroll = true
      scroll_factor = 0.15
      clickfinger_behavior = true
  }
  accel_profile = flat
}

device {
  name = glorious-model-o
  sensitivity = -0.2
  accel_profile = flat
}
